# Exploration

In [20]:
import sys, math
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from scrape import cpm_scraper, stats_scraper

## CPM

In [ ]:
cpm = cpm_scraper.parse_cpm_table(cpm_scraper.fetch_html())
cpm.head()

   level     value
0    1.0  0.094000
1    1.5  0.135137
2    2.0  0.166398
3    2.5  0.192651
4    3.0  0.215732

## Pokemon base stats

In [17]:
pokemon = stats_scraper.parse_entries(stats_scraper.load_raw(PROJECT_ROOT / "pokemon.json"))
pokemon[pokemon["types"].apply(len) == 1]

,index,number,form_id,name,slug,types,hp,attack,defense,is_variant
5,5,4,96,Charmander,4-charmander,[Fire],118,116,93,False
6,6,4,302,Charmander (Fall 2019),4-charmander/fall-2019,[Fire],118,116,93,False
7,7,5,205,Charmeleon,5-charmeleon,[Fire],151,158,126,False
11,11,7,105,Squirtle,7-squirtle,[Water],127,94,121,False
12,12,7,303,Squirtle (Fall 2019),7-squirtle/fall-2019,[Water],127,94,121,False
...,...,...,...,...,...,...,...,...,...,...
1386,1386,975,1527,Cetitan,975-cetitan,[Ice],347,208,123,False
1388,1388,977,1529,Dondozo,977-dondozo,[Water],312,176,178,False
1395,1395,982,879,Dudunsparce (Three-Segment Form),982-dudunsparce/three-segment-form,[Normal],268,188,150,False
1396,1396,982,880,Dudunsparce (Two-Segment Form),982-dudunsparce/two-segment-form,[Normal],268,188,150,False
1413,1413,999,1549,Gimmighoul,999-gimmighoul,[Ghost],128,140,76,False

# Pokemon CP calculation

In [ ]:
for pkm in ["Lickitung"]:
    level = 50
    r = cpm[cpm["level"] == level].iloc[0]
    multiplier = r["value"]

    row = pokemon[pokemon["name"] == pkm].iloc[0]
    a_iv, d_iv, s_iv = 15, 0, 0
    a, d, s = row["attack"] + a_iv, row["defense"] + d_iv, row["hp"] + s_iv,
    cp = max(10, math.floor((a ) * (d )**0.5 * (s )**0.5 * multiplier**2/ 10))



    print(f"{pkm} @ Level {level}: CP {cp}")

Lickitung @ Level 50: CP 1462